# server.yaml

host_vehicle:  # This should match the name of your node
  ros__parameters:
    server_ip: "128.175.213.230"
    server_port: 2000
    vehicle_blueprint: "vehicle.lincoln.mkz_2017"
    role_name: "host_vehicle"
    color: "255,255,0"
    top_lidar:
      pos:
        x: -0.5
        y: 0.0
        z: 2.0
      channels: "128"
      pps: "1000000"
      rot_freq: 10"
      range: "100"
      publish_topic_name: "/sensing/lidar/top/outlier_filtered/pointcloud"
    gnss:
      pos:
        x: -0.9
        y: 0.0
        z: 1.0
    imu:
      pos:
        x: -0.9
        y: 0.0
        z: 1.0
    camera_front:
      pos:
        x: 0.5
        y: 0.0
        z: 2.0
      publish_topic_name: "/sensing/camera/camera0/image_rect_color"  
    enable_top_lidar: True
    enable_front_camera: True
    enable_gnss: False
    enable_imu: False
    enable_v2x: False
    autopilot: False





